// Save as: app/api/export-pdf/route.js

import { NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'

export async function POST(request) {
  try {
    const { title, content, toolName } = await request.json()

    // Create PDF document
    const doc = new PDFDocument({
      margin: 50,
      size: 'LETTER'
    })

    // Collect PDF data chunks
    const chunks = []
    doc.on('data', (chunk) => chunks.push(chunk))

    // Header
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text(title, { align: 'center' })
    
    doc.moveDown(0.5)
    
    // Tool name and date
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#666666')
      .text(`Generated by ${toolName || 'Teacher AI Assistant'} • ${new Date().toLocaleDateString()}`, { align: 'center' })
    
    doc.moveDown(1)
    
    // Divider line
    doc
      .strokeColor('#cccccc')
      .lineWidth(1)
      .moveTo(50, doc.y)
      .lineTo(562, doc.y)
      .stroke()
    
    doc.moveDown(1)

    // Content - parse and format
    doc.fillColor('#000000')
    
    const lines = content.split('\n')
    
    for (const line of lines) {
      const trimmedLine = line.trim()
      
      // Skip empty lines but add spacing
      if (!trimmedLine) {
        doc.moveDown(0.5)
        continue
      }
      
      // Headers (lines with === or ---)
      if (trimmedLine.match(/^[═=]{3,}$/)) {
        doc
          .strokeColor('#cccccc')
          .lineWidth(2)
          .moveTo(50, doc.y)
          .lineTo(562, doc.y)
          .stroke()
        doc.moveDown(0.5)
        continue
      }
      
      if (trimmedLine.match(/^[-─]{3,}$/)) {
        doc
          .strokeColor('#eeeeee')
          .lineWidth(1)
          .moveTo(50, doc.y)
          .lineTo(562, doc.y)
          .stroke()
        doc.moveDown(0.5)
        continue
      }
      
      // Section headers (ALL CAPS or ending with :)
      if (trimmedLine === trimmedLine.toUpperCase() && trimmedLine.length > 3 && !trimmedLine.match(/^\d/)) {
        doc.moveDown(0.5)
        doc
          .fontSize(14)
          .font('Helvetica-Bold')
          .text(trimmedLine)
        doc.moveDown(0.3)
        doc.font('Helvetica').fontSize(11)
        continue
      }
      
      // Headers with colons
      if (trimmedLine.endsWith(':') && trimmedLine.length < 50) {
        doc.moveDown(0.3)
        doc
          .fontSize(12)
          .font('Helvetica-Bold')
          .text(trimmedLine)
        doc.font('Helvetica').fontSize(11)
        continue
      }
      
      // Numbered items (1. 2. 3. etc)
      if (trimmedLine.match(/^\d+\.\s/)) {
        doc
          .fontSize(11)
          .font('Helvetica')
          .text(trimmedLine, { indent: 20 })
        continue
      }
      
      // Bullet points
      if (trimmedLine.startsWith('•') || trimmedLine.startsWith('-') || trimmedLine.startsWith('*')) {
        doc
          .fontSize(11)
          .font('Helvetica')
          .text(trimmedLine, { indent: 20 })
        continue
      }
      
      // Checkbox items
      if (trimmedLine.startsWith('☐') || trimmedLine.startsWith('☑') || trimmedLine.startsWith('✓') || trimmedLine.startsWith('✗')) {
        doc
          .fontSize(11)
          .font('Helvetica')
          .text(trimmedLine, { indent: 20 })
        continue
      }
      
      // Answer key section
      if (trimmedLine.toUpperCase().includes('ANSWER KEY')) {
        doc.moveDown(1)
        doc
          .fontSize(14)
          .font('Helvetica-Bold')
          .text(trimmedLine, { align: 'center' })
        doc.moveDown(0.5)
        doc.font('Helvetica').fontSize(11)
        continue
      }
      
      // Regular text
      doc
        .fontSize(11)
        .font('Helvetica')
        .text(trimmedLine)
      
      // Check if we need a new page
      if (doc.y > 700) {
        doc.addPage()
      }
    }

    // Footer on each page
    const pageCount = doc.bufferedPageRange().count
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i)
      doc
        .fontSize(9)
        .fillColor('#999999')
        .text(
          `Page ${i + 1} of ${pageCount}`,
          50,
          doc.page.height - 50,
          { align: 'center' }
        )
    }

    // Finalize PDF
    doc.end()

    // Wait for PDF to be fully generated
    const pdfBuffer = await new Promise((resolve) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks))
      })
    })

    // Return PDF
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf"`,
      },
    })
  } catch (error) {
    console.error('PDF export error:', error)
    return NextResponse.json({ error: 'Failed to export PDF' }, { status: 500 })
  }
}